project_id = "jlqocytwodbbebrgboaw"

[functions.process-document]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.predict-analytics]
verify_jwt = true

[functions.admin-update-password]
verify_jwt = true

[functions.check-license-expiry]
verify_jwt = false
