// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlqocytwodbbebrgboaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscW9jeXR3b2RiYmVicmdib2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzc0NDcsImV4cCI6MjA2OTgxMzQ0N30.scABCkC-9p-zaAT7JTz38BxNZrMU75GItfuMY9jgW4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});